// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1tjYjZ4IsAt-LvaTAM-KQI7r-xV61xI8',
    appId: '1:662006405635:web:622b20abc1adab78ea0c36',
    messagingSenderId: '662006405635',
    projectId: 'jupiter-test-796b1',
    authDomain: 'jupiter-test-796b1.firebaseapp.com',
    storageBucket: 'jupiter-test-796b1.appspot.com',
    measurementId: 'G-8E1P6L8L9Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDE8IavGqJWYDTC7gik9PzFZGOxdmJB2v0',
    appId: '1:662006405635:android:a37eb6fe68ba9b79ea0c36',
    messagingSenderId: '662006405635',
    projectId: 'jupiter-test-796b1',
    storageBucket: 'jupiter-test-796b1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcT9acuaswbT8WlP-7XoD0OsHrESFQDPo',
    appId: '1:662006405635:ios:5719e0761bc3c470ea0c36',
    messagingSenderId: '662006405635',
    projectId: 'jupiter-test-796b1',
    storageBucket: 'jupiter-test-796b1.appspot.com',
    iosBundleId: 'com.example.jupiterAcademy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcT9acuaswbT8WlP-7XoD0OsHrESFQDPo',
    appId: '1:662006405635:ios:5719e0761bc3c470ea0c36',
    messagingSenderId: '662006405635',
    projectId: 'jupiter-test-796b1',
    storageBucket: 'jupiter-test-796b1.appspot.com',
    iosBundleId: 'com.example.jupiterAcademy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1tjYjZ4IsAt-LvaTAM-KQI7r-xV61xI8',
    appId: '1:662006405635:web:83caa393b86f6de4ea0c36',
    messagingSenderId: '662006405635',
    projectId: 'jupiter-test-796b1',
    authDomain: 'jupiter-test-796b1.firebaseapp.com',
    storageBucket: 'jupiter-test-796b1.appspot.com',
    measurementId: 'G-2TPL06GYT9',
  );

}